"""LLM generation layer with RAG context injection."""

from __future__ import annotations

import os
import uuid
from typing import Any

from brain.types import RetrievalResult
from coltex_platform.config import load_config


RAG_SYSTEM_PROMPT = """You are Coltex, an enterprise RAG assistant. Answer using ONLY the provided context.
If the context does not contain enough information, say so clearly and suggest what documentation might help.
Always cite sources by document title when referencing specific facts.
Be precise, professional, and concise."""


class LLMService:
    def __init__(self, config: dict[str, Any] | None = None):
        self.config = config or load_config()
        self.llm_cfg = self.config.get("llm", {})

    @property
    def model(self) -> str:
        return self.llm_cfg.get("model", "coltex-rag-v1")

    def generate(
        self,
        user_message: str,
        retrieval: RetrievalResult | None = None,
        history: list[dict[str, str]] | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> tuple[str, dict[str, int]]:
        provider = self.llm_cfg.get("provider", "mock")
        temp = temperature if temperature is not None else float(self.llm_cfg.get("temperature", 0.2))
        max_tok = max_tokens or int(self.llm_cfg.get("max_tokens", 2048))
        context = retrieval.context if retrieval else ""
        system = RAG_SYSTEM_PROMPT
        if context:
            system += f"\n\n## Retrieved Context\n\n{context[:12000]}"

        if provider == "openai":
            return self._openai_generate(system, user_message, history or [], temp, max_tok)
        return self._mock_generate(user_message, retrieval, history or [])

    def _mock_generate(
        self,
        user_message: str,
        retrieval: RetrievalResult | None,
        history: list[dict[str, str]],
    ) -> tuple[str, dict[str, int]]:
        if retrieval and retrieval.documents:
            top = retrieval.documents[0]
            doc = top.document
            answer = (
                f"Based on **{doc.title}** (relevance {top.score:.2f}), here is what Coltex found:\n\n"
                f"{doc.content[:800].strip()}\n\n"
                f"*This response was generated by Coltex RAG-as-a-Service using {len(retrieval.documents)} "
                f"retrieved documents. Connect an OpenAI-compatible provider for full LLM generation.*"
            )
        else:
            answer = (
                "I could not find relevant documents in this collection for your question. "
                "Try ingesting more content or broadening your query."
            )
        usage = {
            "prompt_tokens": len(user_message.split()) + 200,
            "completion_tokens": len(answer.split()),
            "total_tokens": len(user_message.split()) + len(answer.split()) + 200,
        }
        return answer, usage

    def _openai_generate(
        self,
        system: str,
        user_message: str,
        history: list[dict[str, str]],
        temperature: float,
        max_tokens: int,
    ) -> tuple[str, dict[str, int]]:
        try:
            import httpx
        except ImportError as exc:
            raise RuntimeError("httpx required for OpenAI provider") from exc

        api_key = os.environ.get(self.llm_cfg.get("openai_api_key_env", "OPENAI_API_KEY"), "")
        if not api_key:
            raise RuntimeError("OPENAI_API_KEY not set")

        base_url = self.llm_cfg.get("openai_base_url", "https://api.openai.com/v1").rstrip("/")
        messages = [{"role": "system", "content": system}]
        messages.extend(history)
        messages.append({"role": "user", "content": user_message})

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        }
        with httpx.Client(timeout=120.0) as client:
            resp = client.post(
                f"{base_url}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()

        choice = data["choices"][0]["message"]["content"]
        usage = data.get("usage", {})
        return choice, {
            "prompt_tokens": usage.get("prompt_tokens", 0),
            "completion_tokens": usage.get("completion_tokens", 0),
            "total_tokens": usage.get("total_tokens", 0),
        }

    @staticmethod
    def new_chat_id() -> str:
        return f"chatcmpl-{uuid.uuid4().hex[:24]}"
